sonata_admin:
    title_logo: '/images/logo.png'
    title: 'ATC SYSTEM'
    templates:
        edit: "extensions.html.twig"
        user_block: 'user_block.html.twig'
    assets:
        stylesheets:
            - bundles/sonatacore/vendor/bootstrap/dist/css/bootstrap.min.css
            - bundles/sonatacore/vendor/components-font-awesome/css/font-awesome.min.css
            - bundles/sonatacore/vendor/ionicons/css/ionicons.min.css
            - bundles/sonataadmin/vendor/admin-lte/dist/css/AdminLTE.min.css
            - bundles/sonataadmin/vendor/admin-lte/dist/css/skins/skin-black.min.css
            - bundles/sonataadmin/vendor/iCheck/skins/square/blue.css
            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css
            - bundles/sonataadmin/vendor/jqueryui/themes/base/jquery-ui.css
            - bundles/sonatacore/vendor/select2/select2.css
            - bundles/sonatacore/vendor/select2-bootstrap-css/select2-bootstrap.min.css
            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css
            - bundles/sonataadmin/css/styles.css
            - bundles/sonataadmin/css/layout.css
            - bundles/sonataadmin/css/tree.css
            - bundles/sonataadmin/css/colors.css
            - '/css/styles.css'
    dashboard:
        groups:
            Главная:
                on_top: true
                icon: '<i class="fa fa-home"></i>'
                items:
                - route: sonata_admin_dashboard
                  label: Главная
            Управление маршрутами:
                label:                Управление маршрутами
                label_catalogue:      ~
                items:
                    - admin.line
                    - admin.station
                    - admin.driver
                    - admin.vehicle

        blocks:
            - { type: sonata.admin.block.admin_list, position: left, settings: { groups: [Управление маршрутами] } }

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
